package cl.corfo.tramitesbech;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidacionBechVO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("N\u00FAmero de Solicitudes realizadas por la Empresa")
   private java.lang.Integer numSolicitudes;

   @org.kie.api.definition.type.Label("Si la empresa es Invitada al PMV")
   private java.lang.Boolean empresaInvitada;

   @org.kie.api.definition.type.Label("Si la empresa tiene reparos")
   private java.lang.Boolean reparo;

   @org.kie.api.definition.type.Label(value = "Indica si sobrepasa el l\u00EDmite m\u00E1ximo")
   private java.lang.Boolean maxSolicitudes;

   public ValidacionBechVO()
   {
   }

   public java.lang.Integer getNumSolicitudes()
   {
      return this.numSolicitudes;
   }

   public void setNumSolicitudes(java.lang.Integer numSolicitudes)
   {
      this.numSolicitudes = numSolicitudes;
   }

   public java.lang.Boolean getEmpresaInvitada()
   {
      return this.empresaInvitada;
   }

   public void setEmpresaInvitada(java.lang.Boolean empresaInvitada)
   {
      this.empresaInvitada = empresaInvitada;
   }

   public java.lang.Boolean getReparo()
   {
      return this.reparo;
   }

   public void setReparo(java.lang.Boolean reparo)
   {
      this.reparo = reparo;
   }

   public java.lang.Boolean getMaxSolicitudes()
   {
      return this.maxSolicitudes;
   }

   public void setMaxSolicitudes(java.lang.Boolean maxSolicitudes)
   {
      this.maxSolicitudes = maxSolicitudes;
   }

   public ValidacionBechVO(java.lang.Integer numSolicitudes,
         java.lang.Boolean empresaInvitada, java.lang.Boolean reparo,
         java.lang.Boolean maxSolicitudes)
   {
      this.numSolicitudes = numSolicitudes;
      this.empresaInvitada = empresaInvitada;
      this.reparo = reparo;
      this.maxSolicitudes = maxSolicitudes;
   }

}